
POST  http://localhost:5000/api/collectors/ HTTP/1.1
Content-Type: application/json

{
    "name": "James Bond",
    "email": "James.bond@mi6.gov.uk",
    "cars": "Aston Martin, BMW",
    "Slogan": "Live and let die",
    "trading": false

}
